config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :bookmarks

      resources :products

      resources :categories

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :bookmarks
  resources :products
  resources :categories
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # Direct associations

  belongs_to :product

  belongs_to :user

  # Indirect associations

  has_one    :product_type,
             through: :product,
             source: :product_type

  # Validations

  validates :category_id, presence: true

  validates :product_id, presence: true

  validates :user_id, presence: true

  # Scopes

  def to_s
    product.to_s
  end
end

app/controllers/api/v1/bookmarks_controller.rb
class Api::V1::BookmarksController < Api::V1::GraphitiController
  def index
    bookmarks = BookmarkResource.all(params)
    respond_with(bookmarks)
  end

  def show
    bookmark = BookmarkResource.find(params)
    respond_with(bookmark)
  end

  def create
    bookmark = BookmarkResource.build(params)

    if bookmark.save
      render jsonapi: bookmark, status: :created
    else
      render jsonapi_errors: bookmark
    end
  end

  def update
    bookmark = BookmarkResource.find(params)

    if bookmark.update_attributes
      render jsonapi: bookmark
    else
      render jsonapi_errors: bookmark
    end
  end

  def destroy
    bookmark = BookmarkResource.find(params)

    if bookmark.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: bookmark
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show edit update destroy]

  def index
    @q = Bookmark.ransack(params[:q])
    @bookmarks = @q.result(distinct: true).includes(:user, :product,
                                                    :product_type).page(params[:page]).per(10)
  end

  def show; end

  def new
    @bookmark = Bookmark.new
  end

  def edit; end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    if @bookmark.save
      message = "Bookmark was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @bookmark, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: "Bookmark was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @bookmark.destroy
    message = "Bookmark was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to bookmarks_url, notice: message
    end
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:product_id, :category_id, :user_id)
  end
end

app/views/bookmarks/_bookmark_product_type.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Product Type
  </div>

  <ul class="list-group list-group-flush">
    <% @bookmark.product_type.each do |category| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/categories/<%= category.id %>">
          <%= category %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/bookmarks/_bookmarks_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "bookmarks_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :category_id, "Category" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :category_id_gteq, :class => "form-control", :placeholder => "Category greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :category_id_lteq, :class => "form-control", :placeholder => "Category less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_username_cont, "User username contains" %>
    <%= f.text_field :user_username_cont, :class => "form-control", :placeholder => "User username contains" %>
  </div>

  <div class="form-group">
    <%= f.label :product_product_name_cont, "Product product_name contains" %>
    <%= f.text_field :product_product_name_cont, :class => "form-control", :placeholder => "Product product_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :product_type_category_type_cont, "Product type category_type contains" %>
    <%= f.text_field :product_type_category_type_cont, :class => "form-control", :placeholder => "Product type category_type contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/bookmarks" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#bookmarks_filters">
  Show filters
</a>

app/views/bookmarks/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Bookmark #<%= bookmark.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Product</dt>
      <dd>
        <% if @bookmark.product.present? %>
          <%= link_to bookmark.product, bookmark.product %>
        <% end %>
      </dd>

      <dt>Category</dt>
      <dd><%= bookmark.category_id %></dd>

      <dt>User</dt>
      <dd>
        <% if @bookmark.user.present? %>
          <%= link_to bookmark.user, bookmark.user %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back bookmark, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_bookmark_url(bookmark), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to bookmark, method: :delete, data: { confirm: "Do you really want to delete this bookmark?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(bookmark.updated_at) %> ago
  </div>
</div>

app/views/bookmarks/_form.html.erb
<% was_validated = bookmark.errors.any? %>

<%= form_with(model: bookmark, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% product_class = "form-control" %>
    <% product_was_invalid = bookmark.errors.include?(:product) %>

    <% if was_validated %>
      <% if product_was_invalid %>
        <% product_class << " is-invalid" %>
      <% else %>
        <% product_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :product_id %>
    <%= f.collection_select :product_id, Product.all, :id, :to_s, {}, class: "form-control" %>
    <% if product_was_invalid %>
      <% bookmark.errors.full_messages_for(:product).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = bookmark.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category_id %>
    <%= f.number_field :category_id, class: category_class, placeholder: "Enter category" %>
    <% if category_was_invalid %>
      <% bookmark.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = bookmark.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% bookmark.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/bookmarks/_list_item.html.erb
<%= link_to bookmark, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= bookmark %>
    <small class="text-muted">
      <%= time_ago_in_words(bookmark.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/bookmarks/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Bookmark #<%= @bookmark.id %>
      </h2>

      <div class="card-body">
        <%= render "form", bookmark: @bookmark %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Bookmarks

      <%= link_to new_bookmark_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "bookmarks/bookmarks_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Bookmarks

        <%= link_to new_bookmark_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @bookmarks, partial: "list_item", as: :bookmark %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @bookmarks, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Bookmark
      </h2>

      <div class="card-body">
        <%= render "form", bookmark: @bookmark %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @bookmark, partial: "card", as: :bookmark %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "bookmarks/bookmark_product_type" %>
  </div>
</div>