config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :bookmarks

      resources :products

      resources :categories

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :bookmarks
  resources :products
  resources :categories
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_base64_uploader :image, ImageUploader

  # Direct associations

  has_many   :bookmarks,
             dependent: :destroy

  belongs_to :product_type,
             optional: true,
             class_name: "Category"

  belongs_to :creator,
             optional: true,
             class_name: "User"

  # Indirect associations

  # Validations

  validates :brand, presence: true

  validates :ph_level,
            numericality: { less_than_or_equal_to: 12,
                            greater_than_or_equal_to: 2 }

  validates :product_name, presence: true

  # Scopes

  def to_s
    product_name
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::GraphitiController
  def index
    products = ProductResource.all(params)
    respond_with(products)
  end

  def show
    product = ProductResource.find(params)
    respond_with(product)
  end

  def create
    product = ProductResource.build(params)

    if product.save
      render jsonapi: product, status: :created
    else
      render jsonapi_errors: product
    end
  end

  def update
    product = ProductResource.find(params)

    if product.update_attributes
      render jsonapi: product
    else
      render jsonapi_errors: product
    end
  end

  def destroy
    product = ProductResource.find(params)

    if product.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: product
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).includes(:creator, :product_type,
                                                   :bookmarks).page(params[:page]).per(10)
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      message = "Product was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @product, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    message = "Product was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to products_url, notice: message
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:brand, :product_name, :ph_level,
                                    :description, :purchase_link, :image, :creator_id, :product_type_id, :validated_by_company)
  end
end

app/views/products/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Product #<%= product.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Brand</dt>
      <dd><%= product.brand %></dd>

      <dt>Product name</dt>
      <dd><%= product.product_name %></dd>

      <dt>Ph level</dt>
      <dd><%= product.ph_level %></dd>

      <dt>Description</dt>
      <dd><%= product.description %></dd>

      <dt>Purchase link</dt>
      <dd><%= product.purchase_link %></dd>

      <dt>Image</dt>
      <dd>
        <%= cl_image_tag @product.image, class: "img-fluid" %>
      </dd>

      <dt>Creator</dt>
      <dd>
        <% if @product.creator.present? %>
          <%= link_to product.creator, product.creator %>
        <% end %>
      </dd>

      <dt>Product type</dt>
      <dd>
        <% if @product.product_type.present? %>
          <%= link_to product.product_type, product.product_type %>
        <% end %>
      </dd>

      <dt>Validated by company</dt>
      <dd><%= product.validated_by_company %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back product, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_product_url(product), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to product, method: :delete, data: { confirm: "Do you really want to delete this product?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(product.updated_at) %> ago
  </div>
</div>

app/views/products/_form.html.erb
<% was_validated = product.errors.any? %>

<%= form_with(model: product, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% brand_class = "form-control" %>
    <% brand_was_invalid = product.errors.include?(:brand) %>

    <% if was_validated %>
      <% if brand_was_invalid %>
        <% brand_class << " is-invalid" %>
      <% else %>
        <% brand_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :brand %>
    <%= f.text_field :brand, class: brand_class, placeholder: "Enter brand" %>
    <% if brand_was_invalid %>
      <% product.errors.full_messages_for(:brand).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% product_name_class = "form-control" %>
    <% product_name_was_invalid = product.errors.include?(:product_name) %>

    <% if was_validated %>
      <% if product_name_was_invalid %>
        <% product_name_class << " is-invalid" %>
      <% else %>
        <% product_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :product_name %>
    <%= f.text_field :product_name, class: product_name_class, placeholder: "Enter product name" %>
    <% if product_name_was_invalid %>
      <% product.errors.full_messages_for(:product_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% ph_level_class = "form-control" %>
    <% ph_level_was_invalid = product.errors.include?(:ph_level) %>

    <% if was_validated %>
      <% if ph_level_was_invalid %>
        <% ph_level_class << " is-invalid" %>
      <% else %>
        <% ph_level_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :ph_level %>
    <%= f.text_field :ph_level, class: ph_level_class, placeholder: "Enter ph level" %>
    <% if ph_level_was_invalid %>
      <% product.errors.full_messages_for(:ph_level).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = product.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_area :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% product.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% purchase_link_class = "form-control" %>
    <% purchase_link_was_invalid = product.errors.include?(:purchase_link) %>

    <% if was_validated %>
      <% if purchase_link_was_invalid %>
        <% purchase_link_class << " is-invalid" %>
      <% else %>
        <% purchase_link_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :purchase_link %>
    <%= f.text_field :purchase_link, class: purchase_link_class, placeholder: "Enter purchase link" %>
    <% if purchase_link_was_invalid %>
      <% product.errors.full_messages_for(:purchase_link).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = product.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% product.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% creator_class = "form-control" %>
    <% creator_was_invalid = product.errors.include?(:creator) %>

    <% if was_validated %>
      <% if creator_was_invalid %>
        <% creator_class << " is-invalid" %>
      <% else %>
        <% creator_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :creator_id %>
    <%= f.collection_select :creator_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if creator_was_invalid %>
      <% product.errors.full_messages_for(:creator).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% product_type_class = "form-control" %>
    <% product_type_was_invalid = product.errors.include?(:product_type) %>

    <% if was_validated %>
      <% if product_type_was_invalid %>
        <% product_type_class << " is-invalid" %>
      <% else %>
        <% product_type_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :product_type_id %>
    <%= f.collection_select :product_type_id, Category.all, :id, :to_s, {}, class: "form-control" %>
    <% if product_type_was_invalid %>
      <% product.errors.full_messages_for(:product_type).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% validated_by_company_class = "form-check-input" %>
    <% validated_by_company_was_invalid = product.errors.include?(:validated_by_company) %>

    <% if was_validated %>
      <% if validated_by_company_was_invalid %>
        <% validated_by_company_class << " is-invalid" %>
      <% else %>
        <% validated_by_company_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :validated_by_company, class: "form-check-label" do %>
      <%= f.check_box :validated_by_company, class: validated_by_company_class %> Validated by company
    <% end %>
    <% if validated_by_company_was_invalid %>
      <% product.errors.full_messages_for(:validated_by_company).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/products/_list_item.html.erb
<%= link_to product, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= product %>
    <small class="text-muted">
      <%= time_ago_in_words(product.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/products/_product_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#product_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @product.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <%= link_to bookmark, method: :delete, data: { confirm: "Do you really want to delete this bookmark" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="product_bookmarks_new_form">
        <%= render partial: "products/product_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/products/_product_bookmarks_new_form.html.erb
<%= form_with(model: @bookmark, local: true) do |f| %>

  <%= f.hidden_field :product_id, value: @product.id %>

  <div class="form-group">
    <%= f.label :category_id %>

    <%= f.text_field :category_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create bookmark", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/products/_products_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "products_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :product_name_cont, "Product name contains" %>
    <%= f.text_field :product_name_cont, :class => "form-control", :placeholder => "Product name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :validated_by_company_eq, "Validated by company" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :validated_by_company_eq, "1", checked: ((params[:q] && params[:q][:validated_by_company_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :validated_by_company_eq, "0", checked: ((params[:q] && params[:q][:validated_by_company_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :validated_by_company_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :purchase_link_cont, "Purchase link contains" %>
    <%= f.text_field :purchase_link_cont, :class => "form-control", :placeholder => "Purchase link contains" %>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :ph_level, "Ph level" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :ph_level_gteq, :class => "form-control", :placeholder => "Ph level greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :ph_level_lteq, :class => "form-control", :placeholder => "Ph level less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :brand_cont, "Brand contains" %>
    <%= f.text_field :brand_cont, :class => "form-control", :placeholder => "Brand contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :creator_username_cont, "Creator username contains" %>
    <%= f.text_field :creator_username_cont, :class => "form-control", :placeholder => "Creator username contains" %>
  </div>

  <div class="form-group">
    <%= f.label :product_type_category_type_cont, "Product type category_type contains" %>
    <%= f.text_field :product_type_category_type_cont, :class => "form-control", :placeholder => "Product type category_type contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/products" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#products_filters">
  Show filters
</a>

app/views/products/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Product #<%= @product.id %>
      </h2>

      <div class="card-body">
        <%= render "form", product: @product %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Products

      <%= link_to new_product_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "products/products_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Products

        <%= link_to new_product_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @products, partial: "list_item", as: :product %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @products, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Product
      </h2>

      <div class="card-body">
        <%= render "form", product: @product %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @product, partial: "card", as: :product %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "products/product_bookmarks" %>
  </div>
</div>